version: '3'
services:
        app:
                build: backend/app
                ports:
                        - "8080:80"
        front:
                build: frontend
                depends_on:
                        - app
                ports:
                        - "80:8080"
        
