apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
              - image: microsoft/mssql-server-linux:latest
                env:
                - name: ACCEPT_EUL
                  value: "Y"
                - name: MSSQL_PID
                  value: "Express"
                - name: SA_PASSWORD
                  value: "yourStrong(!)Password"
        name: db
