apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    app: frontend
